# Generated by Django 4.2.13 on 2024-06-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_user_id'),
        ('users', '0002_customuser_alter_friendship_user1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
