# Generated by Django 4.2.13 on 2024-06-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0006_rename_favorite_team_user_my_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='games.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=255),
        ),
    ]
