version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Dockerfile-local
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
#              gunicorn --bind 0.0.0.0:8000 conf.wsgi:application"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/static:/server/static
    ports:
      - "8000:8000"
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile-local
    command: celery -A conf worker --loglevel=info
    depends_on:
      - db
      - redis
      - server
    restart: unless-stopped

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile-local
    command: celery -A conf beat --loglevel=info
    depends_on:
      - db
      - redis
      - server
      - celery_worker
    restart: unless-stopped

volumes:
  postgres_data: