version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Dockerfile-prod
    command: >
      bash -c "python manage.py migrate &&
               gunicorn --bind 0.0.0.0:8000 conf.wsgi:application &
               celery -A conf worker --loglevel=info &
               celery -A conf beat --loglevel=info &
               wait"
    depends_on:
      - redis
    volumes:
      - ./backend/static:/server/static
    ports:
      - "8000:8000"
    restart: unless-stopped
