[django]
secret_key = "change me"
env = "change me"

[celery]
broker_url = "redis://localhost:6379"
result_backend = "redis://localhost:6379"

[init]
email = "abc@abc.com"
nickname = "change_me"
password = "change_me"
client_id = "change_me"
client_secret = "change_me"
client_type = "change_me"
authorization_grant_type = "change_me"
redirect_uris = "change_me"

[database]
name = "change me"
user = "change me"
password = "change me"
host = "127.0.0.1"
port = "5432"

[database.docker]
name = "change me"
user = "change me"
password = "change me"
host = "172.30.0.100"
port = "5432"

[api_keys]
[api_keys.kakao]
client_id = "change me"
client_secret = "change me"

[api_keys.naver]
client_id = "change me"
client_secret = "change me"

[api_keys.apple]
client_id = "change me"
client_secret = "change me"

[aws]
AWS_S3_ACCESS_KEY = ""
AWS_S3_SECRET_KEY = ""
AWS_S3_STORAGE_BUCKET_NAME = ""
AWS_S3_REGION_NAME = ""
AWS_S3_CUSTOM_DOMAIN = ""

[sentry]
dsn_url = ""