version: '3'
services:
  server:
    build:
      context: .
    command: >
      bash -c "service redis-server start &&
               python manage.py migrate &&
               gunicorn --bind 0.0.0.0:8001 conf.wsgi:application &
               celery -A conf worker --loglevel=info &
               celery -A conf beat --loglevel=info &
               wait"
    volumes:
      - ./backend/static:/server/static
    ports:
      - "8001:8001"
      - "16379:6379"
    restart: unless-stopped