# Generated by Django 5.1.2 on 2025-01-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TEST', '테스트'), ('FRIEND_FEEDBACK', '친구의 반응 알림'), ('FRIEND_UPDATE', '친구의 새소식 알림')], default='FRIEND_FEEDBACK', max_length=15),
        ),
    ]
