# Generated by Django 4.2.13 on 2024-06-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets', '0002_alter_ticket_user_id'),
        ('games', '0001_initial'),
        ('users', '0003_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
