# Generated by Django 5.1.2 on 2025-05-13 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinquiry',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
