# Generated by Django 4.2.13 on 2024-06-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_username_alter_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorite_team',
            new_name='my_team',
        ),
    ]
