# Generated by Django 5.1.2 on 2025-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userinquiry_created_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinquiry',
            options={'verbose_name': '사용자 문의', 'verbose_name_plural': '사용자 문의 목록'},
        ),
        migrations.AlterField(
            model_name='userinquiry',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='사용자 문의 내용'),
        ),
        migrations.AlterField(
            model_name='userinquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일 주소'),
        ),
        migrations.AlterField(
            model_name='userinquiry',
            name='title',
            field=models.CharField(max_length=100, verbose_name='사용자 문의 제목'),
        ),
    ]
