# Generated by Django 3.2.18 on 2024-10-04 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team_away',
        ),
        migrations.AddField(
            model_name='game',
            name='team_away',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='games.team'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='game',
            name='team_home',
        ),
        migrations.AddField(
            model_name='game',
            name='team_home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='games.team'),
            preserve_default=False,
        ),
    ]
