# Generated by Django 5.1.2 on 2024-12-18 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballpark',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ballparks', to='teams.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='ballpark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='games', to='games.ballpark'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_games', to='teams.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_games', to='teams.team'),
        ),
    ]
