# Generated by Django 3.2.18 on 2024-10-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20241004_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ballpark',
        ),
        migrations.AddField(
            model_name='game',
            name='ballpark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.ballpark'),
            preserve_default=False,
        ),
    ]
