# Generated by Django 5.1.2 on 2024-11-19 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('result', models.CharField(choices=[('승리', '승리'), ('패배', '패배'), ('무승부', '무승부'), ('취소', '취소')], max_length=10)),
                ('weather', models.CharField(choices=[('맑음', '맑음'), ('흐림', '흐림'), ('비', '비'), ('바람', '바람')], max_length=30)),
                ('is_ballpark', models.BooleanField(default=True)),
                ('score_our', models.IntegerField(default=0)),
                ('score_opponent', models.IntegerField(default=0)),
                ('starting_pitchers', models.CharField(max_length=255)),
                ('gip_place', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('food', models.CharField(blank=True, max_length=255, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('is_homeballpark', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ballpark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.ballpark')),
                ('game', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_game', to='games.game')),
                ('opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_opponent', to='games.game')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
