# Generated by Django 5.1.2 on 2025-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="only_me",
            field=models.BooleanField(default=True),
        ),
    ]
