# Generated by Django 5.1.2 on 2025-02-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_ticket_only_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_double",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="only_me",
            field=models.BooleanField(default=False),
        ),
    ]
