# Generated by Django 5.1.2 on 2025-02-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_ticket_is_double_alter_ticket_only_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
