# Generated by Django 5.1.2 on 2025-03-01 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_initial"),
        ("tickets", "0005_ticket_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="opponent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_team_away",
                to="games.game",
            ),
        ),
    ]
