# Generated by Django 3.2.18 on 2024-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20241004_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='result',
            field=models.CharField(choices=[('승리', '승리'), ('패배', '패배'), ('무승부', '무승부'), ('취소', '취소')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='weather',
            field=models.CharField(choices=[('맑음', '맑음'), ('흐림', '흐림'), ('비', '비'), ('바람', '바람')], max_length=30),
        ),
    ]
