# Generated by Django 3.2.18 on 2024-10-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20241004_1637'),
        ('tickets', '0007_auto_20241005_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_game', to='games.game'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_opponent', to='games.game'),
        ),
    ]
