# Generated by Django 5.1.2 on 2025-03-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_initial"),
        ("tickets", "0007_alter_ticket_opponent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ballpark",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_ballpark",
                to="games.ballpark",
            ),
        ),
    ]
