# Generated by Django 5.1.2 on 2025-03-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0008_alter_ticket_ballpark"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="direct_away_team",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="ticket",
            name="direct_home_team",
            field=models.CharField(default="", max_length=30),
        ),
    ]
