# Generated by Django 5.1.2 on 2025-03-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0009_ticket_direct_away_team_ticket_direct_home_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="direct_yn",
            field=models.BooleanField(default=False),
        ),
    ]
