# Generated by Django 5.1.2 on 2025-03-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0010_ticket_direct_yn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="direct_away_team",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="direct_home_team",
        ),
        migrations.AddField(
            model_name="ticket",
            name="awayteam_id",
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name="ticket",
            name="hometeam_id",
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_cheer",
            field=models.BooleanField(default=False),
        ),
    ]
