# Generated by Django 5.1.2 on 2025-03-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0010_ticket_direct_yn"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_cheer_home",
            field=models.BooleanField(default=False),
        ),
    ]
