# Generated by Django 5.1.2 on 2025-03-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0011_remove_ticket_direct_away_team_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="angry",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="haha",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="like",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="love",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="sad",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="wow",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="yay",
        ),
        migrations.AddField(
            model_name="ticket",
            name="clap",
            field=models.IntegerField(default=0, help_text="박수 이모지"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="confused",
            field=models.IntegerField(default=0, help_text="혼란 이모지"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="dislike",
            field=models.IntegerField(default=0, help_text="싫은 이모지"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="good",
            field=models.IntegerField(default=0, help_text="따봉 이모지"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="laugh",
            field=models.IntegerField(default=0, help_text="웃음 이모지"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="petulance",
            field=models.IntegerField(default=0, help_text="짜증 이모지"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="point_up",
            field=models.IntegerField(default=0, help_text="검지 손가락 위 이모지"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="rage",
            field=models.IntegerField(default=0, help_text="격노 이모지"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="wink",
            field=models.IntegerField(default=0, help_text="윙크 이모지"),
        ),
    ]
