# Generated by Django 4.2.13 on 2024-05-30 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ballpark', models.IntegerField()),
                ('ballpark', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('starting_pitchers', models.CharField(max_length=255)),
                ('food', models.CharField(max_length=255)),
                ('memo', models.TextField()),
                ('is_home', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
