# Generated by Django 4.2.13 on 2024-06-09 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_alter_ticket_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, choices=[('메롱', '매롱'), ('웃음', '웃음'), ('화남', '화남'), ('욕설', '욕설'), ('불쾌', '불쾌'), ('엄지척', '엄지척'), ('위손가락', '위손가락'), ('엄지아래', '엄지아래'), ('박수', '박수')], max_length=30)),
                ('comment', models.TextField()),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
                ('writer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
