# Generated by Django 3.2.18 on 2024-09-24 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('tickets', '0002_alter_ticket_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='place',
            new_name='gip_place',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_home',
        ),
        migrations.AddField(
            model_name='ticket',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_homeballpark',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.team'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='score_opponent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='score_our',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='weather',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ballpark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.ballpark'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_ballpark',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='result',
            field=models.IntegerField(default=0),
        ),
    ]
