# Generated by Django 3.2.18 on 2024-10-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_user_id_ticket_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='food',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='gip_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
