# Generated by Django 5.1.2 on 2024-12-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('social_id', models.BigIntegerField()),
                ('social_user', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'NONE'), (1, 'NAVER'), (2, 'KAKAO')], verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
