# Generated by Django 5.1.2 on 2025-01-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialinfo',
            name='social_user',
        ),
    ]
