# Generated by Django 3.2.18 on 2024-10-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_auto_20241022_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialinfo',
            name='social_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
