# Generated by Django 5.1.2 on 2025-02-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_remove_socialinfo_social_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialinfo',
            name='social_id',
            field=models.CharField(max_length=100),
        ),
    ]
